name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOVERSION:
          - 1.13
          - 1.14
          - 1.15
          - 1.16
    needs:
      - dep
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.GOVERSION }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: |
          go test -short $(go list ./... | grep -Ev 'vendor|examples')