name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOVERSION:
          - 1.13
          - 1.14
          - 1.15
          - 1.16
    needs:
      - dep
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.GOVERSION }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: |
          go test -short $(go list ./... | grep -Ev 'vendor|examples')

  coverage:
    runs-on: ubuntu-latest
    needs:
      - dep
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: |
          export PKG_LIST=$(go list ./... | grep -Ev 'vendor|examples')
          mkdir cover
          for package in ${PKG_LIST}; do go test -covermode=count -coverprofile "cover/${package##*/}.cov" "$package" ; done
          echo 'mode: count' > coverage.cov
          tail -q -n +2 cover/*.cov >> coverage.cov
          go tool cover -func=coverage.cov
          go tool cover -html=coverage.cov -o index.html

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-browser
          path: index.html

  lint:
    runs-on: ubuntu-latest
    needs:
      - dep
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.0

  compile-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOVERSION:
          - 1.13
          - 1.14
          - 1.15
          - 1.16
    needs:
      - dep
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.GOVERSION }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: |
          go build ./examples/helix-passthru/main.go
          go build ./examples/raw-receive/main.go
          go build ./examples/save-latests/main.go